swagger: "2.0"
info:
  description: ""
  version: "1.0.0"
  title: "Thailand_doc"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
  - name: "Thailand"
    description: "Thailand visa information"    
shemes:
- "http"
paths:          
  /Thailand/consulate:
    get:
      tags: 
      - "Thailand"
      summary: "Get consulation data"
      description: ""
      produces:
      - "application/json" 
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Consulate"
        "404":
          description: "Data not found"               
  /Thailand/visa-center:
    get:
      tags: 
      - "Thailand"
      summary: "Get visa centre data"
      description: ""
      produces:
      - "application/json"      
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/VisaCentre" 
        "404":
          description: "Data not found"          
  /Thailand/news:
    get:
      tags: 
      - "Thailand"
      summary: "Get news data"
      description: ""
      produces:
      - "application/json"        
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/News"
        "404":
          description: "Data not found"            
definitions:
  VisaCentre:
    type: "object"
    properties:
      email:
        type: "string"
      phone:
        type: "string"
      adress:
        type: "string"
      time:
        type: "array"
        items: 
          type: "string"
      info:
        type: "string"
  Consulate:
    type: "object"
    properties:
      adress:
        type: "string"
      phone:
        type: "array"
        items:
          type: "string"         
      email: 
        type: "string"
  News:
    type: "array"
    items:
      $ref: "#/definitions/News_item"
  News_item:
    type: "object"
    properties:
      date:
        type: "string"
      news:
        type: "string"
      news_link: 
        type: "string"
  