
version: '3'

services:
  postgres:
    image: postgres
    container_name: postgres
    user: postgres
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-h', 'localhost', '-U', 'postgres']
    networks:
      - postgres

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=amdin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - postgres

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.2
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-net
    ports:
      - 9200:9200

  kibana:
      container_name: kb-container
      image: docker.elastic.co/kibana/kibana:8.2.2
      environment:
        - ELASTICSEARCH_HOSTS=http://es-container:9200
      networks:
        - es-net
      depends_on:
        - elasticsearch
      ports:
        - 5601:5601

networks:
  postgres:
    driver: bridge
  es-net:
    driver: bridge
