\i postgresql/create_database.sql
\i postgresql/create_country.sql
\i postgresql/create_news_details.sql
\i postgresql/create_category.sql
\i postgresql/create_subcategory.sql
\i postgresql/create_visa_application_centre.sql
\i postgresql/create_appointment.sql
\i postgresql/create_consulate.sql
\i postgresql/create_news.sql
