CREATE TABLE IF NOT EXISTS COUNTRY (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(50) 
);


CREATE TABLE IF NOT EXISTS CONSULATE (
  ID SERIAL PRIMARY KEY,
  COUNTRY_ID INTEGER ,
  ADRESS VARCHAR(200) ,
  EMAIL VARCHAR(70) ,
  WORKING_HOURS VARCHAR(100),
  PHONE_NUMBER_1 VARCHAR(20) ,
  PHONE_NUMBER_2 VARCHAR(20) ,
  FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
);

CREATE TABLE IF NOT EXISTS VISA_APPLICATION_CENTRE (
ID SERIAL PRIMARY KEY,
COUNTRY_ID INTEGER,
ADRESS VARCHAR(200),
EMAIL VARCHAR(70),
APPLY_WORKING_HOURS VARCHAR(100),
ISSUE_WORKING_HOURS VARCHAR(100),
PHONE_NUMBER VARCHAR(20),
FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID)
);

CREATE TABLE IF NOT EXISTS NEWS_DETAILS (
ID SERIAL PRIMARY KEY,
TITLE VARCHAR(70),
BODY VARCHAR(150),
LINK VARCHAR(80)
);

CREATE TABLE IF NOT EXISTS NEWS (
ID SERIAL PRIMARY KEY,
COUNTRY_ID INTEGER,
NEWS_ID INTEGER,
DATE timestamp,
FOREIGN KEY (COUNTRY_ID) REFERENCES COUNTRY (ID),
FOREIGN KEY (NEWS_ID) REFERENCES NEWS_DETAILS (ID)
);