version: '3.9'

services:
  Elasticsearch:
    image: elasticsearch:7.16.2
    container_name: elasticsearch
    restart: always
    volumes:
    - elastic_data:/usr/share/elasticsearch/data/

    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    ports:
    - '9200:9200'
    - '9300:9300'
  
  #Kibana:
  #  image: kibana:7.16.2
  #  container_name: kibana
  #  restart: always
  #  ports:
  #  - '5601:5601'
  #  environment:
  #    - ELASTICSEARCH_URL=http://elasticsearch:9200
  #  depends_on:
  #    - Elasticsearch
  
  selenium:
    image: selenium/standalone-firefox:latest
    ports:
    - 4444:4444
    shm_size: '1gb'
    restart: always
    environment:
      VNC_NO_PASSWORD: 1

  app:
    build:
      context: .
      dockerfile: Dockerfile-app
    volumes:
    - ./app:/app
    ports:
      - 5050:5050

    command: sh -c "python3 app.py"
    depends_on:
    - selenium
    - Elasticsearch

  parser:
    build:
      context: .
      dockerfile: Dockerfile-parser
    volumes:
    - ./app:/app
    command: sh -c "python3 parser.py"
    restart: always
    depends_on:
    - selenium
    - Elasticsearch

volumes:
  elastic_data: {}
  postgres-data:

networks:
  app-network:
    driver: bridge
